version: "3.1"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      
  phpMyAdmin:
   image: phpmyadmin
   environment:
    PMA_ARBITRARY: 1
   ports:
    - "3002:80"


